### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by alcohol49** [alcohol49/AssignmentAirQuality#1]
2022-01-03 15:30:13.079 9842-9842/com.mch.ubiquiti E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mch.ubiquiti, PID: 9842
    java.lang.NumberFormatException: For input string: ""
        at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.mch.ubiquiti.ui.MainViewModel$1.invokeSuspend(MainViewModel.kt:20)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by alcohol49** [comment]
Fixed 81067a730d3fa2263ba3ed6591eb1417f58f5a5a
